spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/kemao_2?useSSL=false&serverTimezone=CST&allowPublicKeyRetrieval=true
      username: kemao_2
      password: 1234
      
   redis: 
      host: 47.102.121.224
      port: 6379
      database: 15
   
   
server.port: 8090
   
   
